language: node_js
node_js:
  - '4.3'
  - '6.9.5'
  - '7'


sudo: required
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25

env:
  - HELPER=Protractor
  - HELPER=Nightmare
  - HELPER=SeleniumWebdriver
  - HELPER=WebDriverIO
  - HELPER=Appium

addons:
  apt:
    packages:
      - php5-cli

services:
  - docker

before_install:
  - docker pull selenium/standalone-chrome:2.53.0

before_script:
  - npm i -g appium
  - npm i -g appium-doctor
  - appium-doctor
  - docker run -d --net=host selenium/standalone-chrome:2.53.0
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod -R 777 test/data
  - "php -S 127.0.0.1:8000 -t test/data/app >/dev/null 2>&1 &"
  - sleep 10

script:
  - gulp test
  - '[[ "$TRAVIS_NODE_VERSION" == "4.3" ]] || ./node_modules/.bin/mocha test/helper/${HELPER}_test.js'
