language: node_js
node_js:
  - '4.3'
  - '6.9.5'
  - '7'

sudo: required
dist: trusty

os:
  - linux

env:
  - HELPER=Protractor
  - HELPER=Nightmare
  - HELPER=SeleniumWebdriver
  - HELPER=WebDriverIO
  - HELPER=Appium

addons:
  apt:
    packages:
      - php5-cli

services:
  - docker

before_install:
  - docker pull selenium/standalone-chrome:2.53.0
  - docker pull butomo1989/docker-android-x86-7.1.1

before_script:
  - docker run -d --net=host selenium/standalone-chrome:2.53.0
  - docker run --privileged -d -p 6080:6080 -p 4723:4723 -p 5554:5554 -p 5555:5555 -v $PWD/test/data/mobile:/root/tmp -e DEVICE="Nexus 5" -e APPIUM=True butomo1989/docker-android-x86-7.1.1
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod -R 777 test/data
  - "php -S 127.0.0.1:8000 -t test/data/app >/dev/null 2>&1 &"
  - sleep 10

script:
  - gulp test
  - '[[ "$TRAVIS_NODE_VERSION" == "4.3" ]] || ./node_modules/.bin/mocha test/helper/${HELPER}_test.js'
