version: '3'
services:
  test-helpers:
    build: .
    entrypoint: docker/entrypoint node_modules/.bin/mocha --invert --fgrep Appium
    command: test/helper
    working_dir: /codecept
    environment:
      - SITE_URL=http://php:8000
      - SELENIUM_HOST=selenium.chrome
      - SELENIUM_PORT=4444
      - JSON_SERVER_URL=http://json_server:8010
    depends_on:
      - selenium.chrome
      - php
      - json_server
    volumes:
      - .:/codecept

  test-acceptance.webdriverio:
    build: .
    environment:
      - CODECEPT_ARGS=-c codecept.WebDriverIO.js --grep @WebDriverIO
      - SITE_URL=http://php:8000
      - SELENIUM_HOST=selenium.chrome
      - SELENIUM_PORT=4444
    depends_on:
      - php
      - selenium.chrome
    volumes:
      - ./test/acceptance:/tests

  test-acceptance.nightmare:
    build: .
    environment:
      - CODECEPT_ARGS=-c codecept.Nightmare.js --grep @Nightmare
      - SITE_URL=http://php:8000
      - SELENIUM_HOST=selenium.chrome
      - SELENIUM_PORT=4444
    depends_on:
      - php
      - selenium.chrome
    volumes:
      - ./test/acceptance:/tests

  selenium.chrome:
    image: selenium/standalone-chrome:3.5.2-antimony
    ports:
      - 4444:4444

  php:
    image: php:7.0
    command: php -S 0.0.0.0:8000 -t /test/data/app
    ports:
      - 8000:8000
    volumes:
      - ./test:/test

  json_server:
    image: node:alpine
    command: npm run json-server
    working_dir: /codecept
    expose:
      - 8010
    volumes:
      - .:/codecept

