site_name: CodeceptJS
theme:
    name: mkdocs
theme_dir: layout
repo_url: https://github.com/codeception/codeceptjs/
pages:
- Index: 'index.md'
- Quickstart: 
    - 'Overview': 'quickstart/quickstart.md'
    - 'Installation': 'quickstart/installation.md'
    - 'Puppeteer': 'quickstart/puppeteer.md'
    - 'WebDriver': 'quickstart/selenium.md'
    - 'Protractor': 'quickstart/protractor.md'
    - 'Nightmare': 'quickstart/nightmare.md'
- Concepts:
    - 'Basics': 'basics.md'
    - 'Acceptance Testing': 'acceptance.md'
    - 'BDD Testing': 'bdd.md'
    - 'Test Lifecycle': 'lifecycle.md'
    - 'Locators': 'locators.md'
    - 'Debugging': 'debugging.md'
    - 'Helpers': 'helpers.md'
    - 'Page Objects': 'pageobjects.md'
    - 'Data Driven Tests': 'datadriven.md'
    - 'Retries': 'retries.md'
    - 'Multiple Sessions': 'sessions.md'
- Guides:
    - 'Puppeteer Testing': 'puppeteer.md'
    - 'AngularJS Testing': 'angular.md'
    - 'Nightmare Testing': 'nightmare.md'
    - 'Mobile Testing': 'mobile.md'
    - 'Data Management': 'data.md'
    - 'Frames': 'frames.md'
    - 'Drag and Drop': 'drag-drop.md'
    - 'Multiple Browsers': 'multi.md'
    - 'Advanced Usage': 'advanced.md'
- Helpers:
    - 'What is a Helper?': 'what-is-helper.md'
    - 'WebDriver': 'helpers/WebDriver.md'
    - 'Protractor': 'helpers/Protractor.md'
    - 'SeleniumWebdriver': 'helpers/SeleniumWebdriver.md'
    - 'Puppeteer': 'helpers/Puppeteer.md'
    - 'Nightmare': 'helpers/Nightmare.md'
    - 'Appium': 'helpers/Appium.md'
    - 'REST': 'helpers/REST.md'
    - 'ApiDataFactory': 'helpers/ApiDataFactory.md'
    - 'FileSystem': 'helpers/FileSystem.md'
    - 'Reports': 'helpers/Mochawesome.md'
- Reference:
    - 'Installation': 'installation.md'
    - 'Commands': 'commands.md'
    - 'Configuration': 'configuration.md'
    - 'Reports': 'reports.md'
    - 'Translation': 'translation.md'
    - 'Plugins': 'plugins.md'
    - 'Docker': 'docker.md'
    - 'Hooks': 'hooks.md'
    - 'API': 'api.md'
- Releases: 'changelog.md'
copyright: Created by CodeceptJS Team
google_analytics: ['UA-30075781-3','auto']