on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check Tests
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: testomatio/check-tests@master
      with:
        framework: mocha
        tests: '{ test/**_test.js, tests/helper/webapi.js }'
        token: ${{ secrets.GITHUB_TOKEN }}
